### ISSUE TITLE
Not reading refs inside of array items

### ISSUE THREAD

**Issue by KyleDFulton** [yourtion/vue-json-ui-editor#38]
The arrays are not rendering properly.

	"properties": {
		"Name": {
			"type": "string",
                        "title": "Name",
			"minLength": 1
		},
		"Markets": {
			"type": "array",
                        "title": "Markets",
			"items": {
				"$ref": "#/definitions/Market"
				}
		}
         },
	"definitions": {
		"Market": {
			"additionalProperties": false,
			"required": [
				"Name"
			],
			"properties": {
				"Name": {
					"type": "string",
					"minLength": 1
				},
				"EffectiveDate": {
					"type": "string",
					"minLength": 1
				},
				"ExpirationDate": {
					"type": "string"
				}
                    }
           }

**Comment by nmfisher** [comment]
Assume you're not planning to implement this?

**Comment by sibenmao** [comment]
> Assume you're not planning to implement this?

how ? thanks
