### ISSUE TITLE
NPM version is empty

### ISSUE THREAD

**Issue by BenjaminVadant** [yourtion/vue-json-ui-editor#5]
Hi,

it seems that since version 0.1.0, all published version of the package are empty: it only contains the README, License and package.json

Can you publish a new version that does contain the dist folder ?

Thanks

**Comment by yourtion** [comment]
thanks, fixed on 0.9.0 https://github.com/yourtion/vue-json-ui-editor/commit/79699fea1e33e1c1fceb0567b859e79be07d8822
